### ISSUE TITLE
Error rotating sent mail orders

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowershellFrameworkCollective/MailDaemon#3]
Can't multiply timespans with int

**Comment by Stilmant** [comment]
how I believe it is relate to my previous post:
`Method invocation failed because [System.TimeSpan] does not contain a method named ‘op_Multiply.`

**Comment by FriedrichWeinmann** [comment]
Alright ... so it _may_ have taken a bit longer than it really should have.
Slightly.
But v1.0.1 just shipped and finally fixed this.

I definitely didn't forget this project existed. Promise!
...
_sorry!_
